### ISSUE TITLE
Awareness in zustand-yjs

### ISSUE THREAD

**Issue by NGimbal** [tandem-pt/zustand-yjs#1]
Have you thought about how to handle awareness in zustand-yjs?

I'm not exactly sure how to implement it... but it seems like it could be another property of the object returned by useYStore(). 

```typescript
const useYStore = create<YStore>((set, get) => {
  return {
    yDocs: [],
    observers: [],
    data: [],
    awareness: []
    ...
```

After you mount the yDoc using their connect function, an event handler is registered on the provider.awareness object and changes are observed similarly to how changes are observed on any of the y objects.

```typescript
      else {
        // const unMount = mount(yDoc)
        const [unMount, provider] = mount(yDoc)
        if(typeof provider !== 'undefined'){
          provider.awareness.on('update', () => {
            set({
              awareness: Array.from(provider.awareness.getStates().values())
            })
          })
        }
        set({ yDocs: [...yDocs, [yDoc.guid, yDoc, mount, unMount, 1]] })
      }
```

Didn't look like this fit with the existing observers array pattern, but let me know if I'm wrong.

I tried to test this out myself but ran into major issues with npm link. Might try again tomorrow.

Thanks!

**Comment by NGimbal** [comment]
So the previous post was a bit naive although I hope I got the idea across... I wasn't able to get npm link to work for some reason, so I ended up implementing a useAwareness hook in my project as below:

```javascript
const useAwareness = (initAwareness) => {
  const [collabs, setCollabs] = useState([])
  const [awareness, setAwareness] = useState(initAwareness)

  useEffect(() => {
    if(typeof awareness !== 'undefined'){
      awareness.on('update', () => {
        setCollabs(Array.from(awareProvider.getStates().values()))
      })
    }
  },[awareness])
  
  return [collabs, setAwareness]
}
```

This seems to work. Let me know what you think about integrating this into zustand-yjs!

**Comment by froger** [comment]
Hello! Thanks, @NGimbal that's a trickier issue than I thought :)

So, I didn't plan to implement awareness that soon, but it seems like a good idea as it's a pretty common feature. 
My understanding of awareness is getting better but is still limited, so here how I see the feature from your examples:


Currently, the connect function looks like this: 
```js
import { WebrtcProvider } from 'y-webrtc'

const connectADoc = (doc: Y.Doc) => {
  console.log('connect ', doc.guid)
  const provider = new WebrtcProvider(`mydoc:${doc.guid}`, ydoc)
  return () => {
    provider.destroy();
  }
}
```

And could looks like: 

```js
import { WebrtcProvider } from 'y-webrtc'

const connectADoc = (doc: Y.Doc, handleAwareness) => {
  console.log('connect ', doc.guid)
  const provider = new WebrtcProvider(`mydoc:${doc.guid}`, ydoc)
  provider.awarenes.on('update', handleAwareness)
  return () => {
    provider.awareness.off('update', handleAwerness); // Optional, as #destroy will do it
    provider.destroy();
  }
}
```

And then to retrieve awareness data, I could create a hook that use the Zustand YStore: 
```js
import { useYDoc, useAwareness } from 'zustand-yjs'

const List = () => {
  const yDoc = useYDoc('root', connectADoc);
  const awarenessStates = useAwareness(yDoc); // Return the stored Awareness#getStates().values()
  return <div>Do stuff with awareness</div>
}
```

My first impressions of this draft are: 
* It's good to have another hook for awareness as you don't need to use it systematically.
* Adding a parameter to the connect function is the simplest thing I have in mind, even I think there is a better solution for the end-user of the library.
* Your snippet will be very helpful, just some adjustments for this API and it should work.
* I think it will add a lot of value to this project :)

What do you think of this draft @NGimbal? Looking at this draft, do you see anything harmful for the lib?

**Comment by NGimbal** [comment]
Awesome! I think what you're describing makes a ton of sense. 

One thing to note: in my snippet initAwareness refers to the awareness object on the yjs provider. This was the most awkward thing about doing it outside of zustand-yjs.

```javascript
  awareProvider = wsProvider.awareness

   awareProvider.setLocalState({ 
      color: chroma.random().hex(),
      name: randomName(),
      clientID: awareProvider.clientID
    })
```

**Comment by NGimbal** [comment]
Okay so I hit the close button accidentally...

What I was wanting to say was that this looks great :) thanks for figuring out the details on this.

One thing I'd want to note (although you probably already realized this) is that in my snippet initAwareness refers to the awareness object that is part of the yjs-provider object. Additionally, the user will want to set an initial state when initiating awareness using yjsProvider.awareness.setLocalState(). I guess in the example you show, that could still take place in connectADoc() as I have it shown below.

```javascript
var awareProvider

const connectDoc = (doc) => {
  const wsProvider = new WebsocketProvider('ws://localhost:1234', 'my-room3', doc)

  awareProvider = wsProvider.awareness

  awareProvider.setLocalState({ 
     color: chroma.random().hex(),
     name: randomName(),
     clientID: awareProvider.clientID
 })

 return () => console.log('disconnect', doc.guid)
}

const useAwareness = (initAwareness) => {
  // as in snippet above above
}

function App() {

  const ydoc = useYDoc('docguid', connectDoc)  
  const [collabs, setAwareness] = useAwareness(awareProvider)
  
  ...
}
```

**Comment by froger** [comment]
Thanks for example @NGimbal, I've seen some problems in my drafts. 

> Additionally, the user will want to set an initial state when initiating awareness using yjsProvider.awareness.setLocalState()

Yes, I thought it could be done in the connect function, like in your example

---

```js
var awareProvider
const connectDoc = (doc) => {
...
```
I would like to design an API that avoids the use of globals like this `var awareProvider`, and I realize with your example that my proposal forces you to do so. My idea is that you can have a unique connect function, that connects all your YDoc. As they have distinct `#guid` you can route the connexion with that name. 

So a global var for `awareProvider` in the case of many `YDoc` connecting won't work. 

---

From your example, and the flaws I saw in my draft, here what I have in mind: 
```js
import { WebrtcProvider } from 'y-webrtc'

const connectDoc = (doc: Y.Doc, startAwareness) => {
  const wsProvider = new WebrtcProvider('ws://localhost:1234 ', `${doc.guid}`, ydoc);
  const awareProvider = wsProvider.awareness;
  awareProvider.setLocalState({ 
     color: chroma.random().hex(),
     name: randomName(),
     clientID: awareProvider.clientID
 })
  // startAwareness will store the provider for the doc.guid, 
  // and starts to do a protocol.awareness.on('update').  
  const stopAwareness = startAwareness(wsProvider);
  
  return () => {
    stopAwareness();
    provider.destroy();
  }
}

function App() {
  const ydoc = useYDoc('my-room3', connectDoc)  
  // useAwareness takes the YDoc, to know the #guid, 
  // and then be able to retrieve the right awareness data.
  // Initial state for awareness would be handle in the connectDoc function and not in the view.
  // @returns awareness#getState data and awareness#setLocalStateField function
  const [awareness, setAwareness] = useAwareness(ydoc)
  
  ...
}
```

===


PR is coming later this week :P quite a lot on my plate right now.

**Comment by dmonad** [comment]
I really like the idea to be able to access and modify awareness state like this. Your awareness API could make it very convenient to render presence information (the list of currently active users).

As mentioned in the Yjs Gitter channel, Awareness is not well suited to store a lot of information. However, it is well suited for data that changes frequently and has a small footprint (e.g. cursor location, the name of the user, and the associated color). It is also nice for storing the caret position in x,y coordinates. Just keep that in mind when designing the API. It might be a bad idea to store all user-associated data in an Awareness field. I should probably put that in the documentation as well.

**Comment by froger** [comment]
Great, thanks for the reminder @dmonad, will have this in mind, I think it's a great use-case for transient values. 
By the way, it reminds me that indeed `useAwareness` should give back a `setLocalStateField` if we want to set awareness haha. Proposal updated, working in on it!

**Comment by meatflavourdev** [comment]
> It might be a bad idea to store all user-associated data in an Awareness field. - @dmonad 

Can you elaborate on this, specifically, why this might not be a best practice?

**Comment by dmonad** [comment]
Every time you change the awareness state, you send your complete local copy to all connected peers. So when you store a profile picture, mail address, street, zip, .. in your awareness instance, then you use more network traffic than you would need to. I recommend to only store data that changes frequently + the name and a user-identifier that you can use to query user-associated data that doesn't change frequently (e.g. profile picture, mail, street zip, ..).

**Comment by froger** [comment]
Hello, just commenting the issue to say I've made it 🎉 (finally).

I did some bad manipulations on the github, so that's why we have made quite a gap in versions, sorry about that. 
I really need to sit to write a pipeline and unit tests, to avoid messy publish. :)

=== 


I am very happy to have done this feature at the end, it gives me really a good feeling using the lib, so thanks @NGimbal. 

Readme is coming soon. For now, in the example, you will see how to edit the local changes : 
https://github.com/tandem-pt/zustand-yjs/blob/master/example/src/App.tsx#L111-L117

And how to use it: 
https://github.com/tandem-pt/zustand-yjs/blob/master/example/src/App.tsx#L81-L89

===

Here the example: 
![out](https://user-images.githubusercontent.com/3929108/111846783-6e177080-88ff-11eb-8cb7-e0f62d0abd53.gif)

**Comment by NGimbal** [comment]
Amazing! 🤩

**Comment by neftaly** [comment]
Thanks for getting this working!
